spring.application.name=Email-Service

#Kafka configuration
spring.kafka.consumer.bootstrap-servers=localhost:9092,localhost:9096
spring.kafka.consumer.key-deserializer= org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer =  org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=product-created-events
spring.kafka.consumer.properties.spring.json.trusted.packages =*    
#com.developer.ws.core
#spring.kafka.consumer.properties.spring.json.type.mapping = ProductCreatedEvent:com.developer.ws.core.ProductCreatedEvent

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

#logging.level.org.springframework.kafka.listener.DefaultErrorHandler=DEBUG
#logging.level.org.springframework.kafka.listener.KafkaMessageListenerContainer=DEBUG
